version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=your-secret-key-here
      - MONGO_URI=mongodb://mongo:27017/resume_ai
      - REDIS_URL=redis://redis:6379/0
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongo
      - redis
    networks:
      - resume-ai-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - resume-ai-network

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - resume-ai-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - resume-ai-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - resume-ai-network

volumes:
  mongo_data:

networks:
  resume-ai-network:
    driver: bridge

